branches:
  only:
    - master

language: objective-c
osx_image: xcode10.2

env:
  global: 
    - PROJECT="Schedule.xcodeproj"
    - SCHEME="Schedule-Package"

matrix:
  include:
    - os: osx
      env:
        - SDK="iphonesimulator12.2"
        - DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=12.2"
    - os: osx
      env:
        - SDK="macosx10.14"
        - DESTINATION="arch=x86_64"
    - os: osx
      env:
        - SDK="appletvsimulator12.0"
        - DESTINATION="OS=12.0,name=Apple TV 4K"
    - os: linux
      sudo: required
      dist: trusty

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      gen install xcpretty
    fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      eval "$(curl -sL https://swiftenv.fuller.li/install.sh)";
    fi

script:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      xcodebuild clean build test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -enableCodeCoverage YES | xcpretty
    fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      swift test
    fi

after_success:
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    bash <(curl -s https://codecov.io/bash) -J 'Schedule';
  fi