branches:
  only:
    - master

osx_image: xcode10
language: generic

matrix:
  include:
    - os: osx
      env:
        - SDK="iphonesimulator12.0"
        - DESTINATION="OS=12.0,name=iPhone X"
    - os: osx
      env:
        - SDK="macosx10.13"
        - DESTINATION="arch=x86_64"
    - os: osx
      env:
        - SDK="watchsimulator5.0"
        - DESTINATION="OS=5.0,name=Apple Watch Series 4 - 44mm"
    - os: osx
      env:
        - SDK="appletvsimulator12.0"
        - DESTINATION="OS=12.0,name=Apple TV 4K"
    - os: linux
      sudo: required
      dist: trusty

before_install:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      gem install xcpretty --no-rdoc --no-ri --no-document --quiet;
    fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      eval "$(curl -sL https://swiftenv.fuller.li/install.sh)";
    fi

script:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      - xcodebuild clean build test -project Schedule.xcodeproj -scheme Schedule-Package -sdk "$SDK" -destination "$DESTINATION" -enableCodeCoverage YES | xcpretty;
    fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
      swift build;
      swift test;
    fi

after_success:
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    bash <(curl -s https://codecov.io/bash) -J 'Schedule';
  fi